# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/jules/Desktop/Travail/VHDL_Master_Camp/Nexys-Video-Master.xdc

# IP: C:/Users/jules/Downloads/basys3_ov7670_v1/basys3_ov7670_v1/basys3_ov7670_v1.srcs/sources_1/ip/frame_buffer/frame_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==frame_buffer || ORIG_REF_NAME==frame_buffer} -quiet] -quiet
